/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MestreModbus */

#ifndef _Included_MestreModbus
#define _Included_MestreModbus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MestreModbus
 * Method:    modbusOpen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MestreModbus_modbusOpen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
