/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MestreModbus */

#ifndef _Included_MestreModbus
#define _Included_MestreModbus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MestreModbus
 * Method:    modbusOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MestreModbus_modbusOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MestreModbus
 * Method:    modbusUpdateFiO2
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_MestreModbus_modbusUpdateFiO2
  (JNIEnv *, jobject, jshort);

/*
 * Class:     MestreModbus
 * Method:    modbusUpdateInsp
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_MestreModbus_modbusUpdateInsp
  (JNIEnv *, jobject, jshort);

/*
 * Class:     MestreModbus
 * Method:    modbusUpdateBpm
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_MestreModbus_modbusUpdateBpm
  (JNIEnv *, jobject, jshort);

/*
 * Class:     MestreModbus
 * Method:    modbusUpdateMaxPaw
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_MestreModbus_modbusUpdateMaxPaw
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
